// players.js
export const PLAYERS = [
    { name: 'Player1', team: 'TeamA', jerseyNumber: 10, type: 'Batsman' },
    { name: 'Player2', team: 'TeamB', jerseyNumber: 7, type: 'Bowler' },
    { name: 'Player3', team: 'TeamC', jerseyNumber: 22, type: 'All-rounder' },
    { name: 'Player4', team: 'TeamA', jerseyNumber: 99, type: 'Wicketkeeper' },
    { name: 'Player5', team: 'TeamB', jerseyNumber: 14, type: 'Batsman' },
    { name: 'Player6', team: 'TeamC', jerseyNumber: 10, type: 'All-rounder' },
    { name: 'Player7', team: 'TeamA', jerseyNumber: 12, type: 'Batsman' },
    { name: 'Player8', team: 'TeamB', jerseyNumber: 77, type: 'Bowler' },
    { name: 'Player9', team: 'TeamC', jerseyNumber: 55, type: 'Wicketkeeper' },
    { name: 'Player10', team: 'TeamA', jerseyNumber: 33, type: 'All-rounder' },
    { name: 'Player11', team: 'TeamB', jerseyNumber: 19, type: 'Batsman' },
    { name: 'Player12', team: 'TeamC', jerseyNumber: 8, type: 'Bowler' },
    { name: 'Player13', team: 'TeamA', jerseyNumber: 91, type: 'Wicketkeeper' },
    { name: 'Player14', team: 'TeamB', jerseyNumber: 27, type: 'All-rounder' },
    { name: 'Player15', team: 'TeamC', jerseyNumber: 42, type: 'Batsman' },
    { name: 'Player16', team: 'TeamA', jerseyNumber: 66, type: 'Bowler' },
    { name: 'Player17', team: 'TeamB', jerseyNumber: 5, type: 'Wicketkeeper' },
    { name: 'Player100', team: 'TeamA', jerseyNumber: 25, type: 'All-rounder' },
    { name: 'Virat Kohli', team: 'India', jerseyNumber: 18, type: 'Batsman' },
    { name: 'Steve Smith', team: 'Australia', jerseyNumber: 49, type: 'Batsman' },
    { name: 'Kane Williamson', team: 'New Zealand', jerseyNumber: 22, type: 'Batsman' },
    { name: 'Jos Buttler', team: 'England', jerseyNumber: 63, type: 'Wicketkeeper' },
    { name: 'Rashid Khan', team: 'Afghanistan', jerseyNumber: 17, type: 'Bowler' },
];
